---
title: Understanding health economics in clinical trials
author: Andrea Gabrio
date: '2019-07-03'
slug: understanding-health-economics-in-clinical-trials
categories: []
tags:
  - Academic
  - Clinical Trials
  - Health economics
  - introduction
subtitle: ''
summary: ''
authors: ["Andrea Gabrio"]
lastmod: '2019-07-03T12:34:03+01:00'
featured: yes
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: [health-economics]
---

As member of the Health Economics Analysis and Research Methods Team (HEART) and together with my colleagues, on Tuesday 2 July 2019 I took part in a 1-day introductory short course entitled “Understanding health economics in clinical trials”. HEART is a new group of health economists who are based in UCL’s Institute of Clinical Trials and Methodology (ICTM), led by [Rachael Hunter](https://iris.ucl.ac.uk/iris/browse/profile?upi=RMHUN48). This short course was aimed at ICTM staff who are not health economists (e.g. trial managers, CIs/PIs, statisticians, data managers, research assistants, etc.). We designed the course in response to the need we have identified over the last few years in working on trials with various trials units in UCL and elsewhere, as well as in response to colleagues across ICTM. This course was unique as it was intended specifically for non health economists working in trials, who wish to better understand the health economics in their study, and/or the health economist on their study.

The course used a mix of lectures, group discussions and practical exercises to help participants consolidate their learning and see how to apply information from the sessions to real studies. No prior knowledge of health economics was assumed. Key topics which were covered during the day were:

* Explain the importance of health economics in clinical trials (aims, objectives, interpretation and limitations)
* Justify collaboration with the health economist on development of trial documents and processes (i.e. protocol, CRFs and analysis plan)
* Identify challenges in data collection for economic evaluations alongside trials (resource use and other cost data)
* Recognise the pros and cons of different patient-reported outcome measures (PROMs)
* Appraise the quality of the health economic evaluation analysis plan (HEAP)
* Check consistency of the protocol’s economic evaluation section with other aspects of the protocol
* Interpret the results of economic evaluations alongside trials

















 
 
 
 
 
 
 
 
 
 
 
 












