---
title: Citations
author: "Andrea Gabrio"
date: '2019-06-23'
slug: citations
categories:
  - R
tags:
  - Academic
subtitle: ''
summary: ''
authors: ["Andrea Gabrio"]
lastmod: '2019-06-23T17:41:24+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
bibliography: [citations.bib]
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(comment = NA, eval = FALSE)

# load packages
packages <- c("bookdown", "blogdown", "knitr")
lapply(packages, function(x) {
  if (!requireNamespace(x)) install.packages(x)
  library(x, character.only = TRUE)
})
```


With **blogdown**, you are able to take advantage of several features of Pandoc's Markdown, including adding citations. You can read more about adding citations in the **bookdown** book [here](https://bookdown.org/yihui/bookdown/citations.html). 

This post will demonstrate how you can add citations. There are 3 steps:

1. Save a BibTeX file(s) in the `/content/post/` directory. The file should be a plain-text file that contains citations that generally look like this

2. Reference the BibTeX file(s) in the YAML header of your post 

3. In the text of your post, reference items in BibTeX file(s) using `@key`

# Example 1: Adding citations for books or articles

There are several ways to export citations for books or articles as a BibTeX file. One simple way is to use [Google Scholar](https://scholar.google.com) to obtain a BibTeX entry. For example, if you search for "Bookdown: Authoring Books and Technical Documents with R Markdown", you can view the citation by clicking on the quote icon underneath the entry. 

If you then click on the BibTeX link, you will see the formatted plain text version, which you can download as a file with the .bib extension. To now cite this item in the text of your post, use the format `@key`, so `@xie2016bookdown` generates: @xie2016bookdown. Notice that you can click on the year to see the full reference.




